export default [
  {
    "_id": "Q101",
    "title": "Q1 - HTML",
    "course": "RS101",
    "description": "This quiz covers basic HTML elements and attributes.",
    "quizType": "Graded Quiz",
    "assignmentGroup": "QUIZZES",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2024-09-21T13:00:00",
    "availableDate": "2024-09-01T00:00:00",
    "untilDate": "2024-09-22T23:59:00",
    "points": 10,
    "published": true,
    "numberOfQuestions": 3
  },
  {
    "_id": "Q102",
    "title": "Q2 - CSS",
    "course": "RS101",
    "description": "This quiz covers CSS selectors, properties, and layouts.",
    "quizType": "Graded Quiz",
    "assignmentGroup": "QUIZZES",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2024-12-05T13:00:00",
    "availableDate": "2024-11-01T00:00:00",
    "untilDate": "2024-12-06T23:59:00",
    "points": 15,
    "published": true,
    "numberOfQuestions": 3
  },
  {
    "_id": "Q201",
    "title": "Q1 - Aerodynamics Basics",
    "course": "RS102",
    "description": "Quiz on fundamental aerodynamics concepts.",
    "quizType": "Graded Quiz",
    "assignmentGroup": "QUIZZES",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": true,
    "howManyAttempts": 3,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2024-11-20T15:00:00",
    "availableDate": "2024-11-01T00:00:00",
    "untilDate": "2024-11-21T23:59:00",
    "points": 12,
    "published": true,
    "numberOfQuestions": 3
  }
];
